import { Prescription } from "./types";

export const mockPrescriptions: Prescription[] = [
  {
    id: "RX-001",
    patientName: "Sarah Johnson",
    patientId: "P-1001",
    region: "US",
    medications: [{ name: "Sertraline", doseMg: 50, frequency: "qd" }],
    status: "active",
    risk: "medium",
    createdAt: "2024-12-05T10:00:00Z",
    pharmacyName: "CVS Pharmacy #1234",
    notes: "Morning dose with food",
    controlledSchedule: "IV",
  },
  {
    id: "RX-002",
    patientName: "Michael Chen",
    patientId: "P-1002",
    region: "US",
    medications: [{ name: "Bupropion", doseMg: 150, frequency: "bid" }],
    status: "active",
    risk: "high",
    createdAt: "2024-12-04T09:30:00Z",
    pharmacyName: "Walgreens #5678",
    controlledSchedule: "III",
  },
  {
    id: "RX-003",
    patientName: "Emily Rodriguez",
    patientId: "P-1003",
    region: "US",
    medications: [{ name: "Alprazolam", doseMg: 0.5, frequency: "prn" }],
    status: "active",
    risk: "critical",
    createdAt: "2024-12-03T08:15:00Z",
    pharmacyName: "Rite Aid #9012",
    notes: "Use only during severe anxiety episodes",
    controlledSchedule: "IV",
  },
  {
    id: "RX-004",
    patientName: "Ahmet Yılmaz",
    patientId: "P-2001",
    region: "TR",
    medications: [{ name: "Paroksetin", doseMg: 20, frequency: "qd" }],
    status: "draft",
    risk: "medium",
    createdAt: "2024-12-02T14:00:00Z",
  },
  {
    id: "RX-005",
    patientName: "Elena Garcia",
    patientId: "P-3001",
    region: "EU",
    medications: [{ name: "Escitalopram", doseMg: 10, frequency: "qd" }],
    status: "expired",
    risk: "low",
    createdAt: "2024-10-10T11:00:00Z",
    notes: "Expired prescription",
  },
];


