// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6dkih6TUiSgfum2ZfwUVhvMsNo8CtMHU',
    appId: '1:721977136900:web:9c085d0348659a067da251',
    messagingSenderId: '721977136900',
    projectId: 'borsailhanos',
    authDomain: 'borsailhanos.firebaseapp.com',
    storageBucket: 'borsailhanos.firebasestorage.app',
    measurementId: 'G-YXYGJ4PHY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4MTpRLBD4hymazoPkqnzNmJHWQolzPek',
    appId: '1:721977136900:android:fb57c782955ee1b27da251',
    messagingSenderId: '721977136900',
    projectId: 'borsailhanos',
    storageBucket: 'borsailhanos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClpP-W1Bq5LnZFsRhmlRkjTdxZInXUzrk',
    appId: '1:721977136900:ios:a3c1e969b5e2d8857da251',
    messagingSenderId: '721977136900',
    projectId: 'borsailhanos',
    storageBucket: 'borsailhanos.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClpP-W1Bq5LnZFsRhmlRkjTdxZInXUzrk',
    appId: '1:721977136900:ios:a3c1e969b5e2d8857da251',
    messagingSenderId: '721977136900',
    projectId: 'borsailhanos',
    storageBucket: 'borsailhanos.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6dkih6TUiSgfum2ZfwUVhvMsNo8CtMHU',
    appId: '1:721977136900:web:5bb2c3997c9c226b7da251',
    messagingSenderId: '721977136900',
    projectId: 'borsailhanos',
    authDomain: 'borsailhanos.firebaseapp.com',
    storageBucket: 'borsailhanos.firebasestorage.app',
    measurementId: 'G-JJP13K4P11',
  );
}
